
export const GET_ACCOUNTS="GET_ACCOUNTS";
export const GET_ACCOUNT="GET_ACCOUNT";
export const GET_DEMANDS="GET_DEMANDS"
export const GET_DEMAND="GET_DEMAND";
export const GET_DEMANDS_ALL="GET_DEMANDS_ALL";
export const GET_DEMANDS_ACCOUNT="GET_DEMANDS_ACCOUNT";
export const GET_DEMANDS_STATUS="GET_DEMANDS_STATUS";
export const GET_DEMANDS_DATE="GET_DEMANDS_DATE";
export const GET_DEMANDS_DATE_ACCOUNT="GET_DEMANDS_DATE_ACCOUNT";
export const GET_DEMANDS_DATE_STATUS="GET_DEMANDS_DATE_STATUS";
export const GET_DEMANDS_ACCOUNT_STATUS="GET_DEMANDS_ACCOUNT_STATUS";
export const LOCATION_CHANGE="LOCATION_CHANGE";
export const SET_CURRENT_USER="SET_CURRENT_USER";
export const GET_ERRORS="GET_ERRORS";