FROM openjdk
MAINTAINER Hakim Arhazzal <hakim.arhazzal@gmail.com>
ADD target/register-service-0.0.1-SNAPSHOT.jar register-service-0.0.1-SNAPSHOT.jar.jar
ENTRYPOINT ["java", "-jar", "/register-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 8765