FROM openjdk
MAINTAINER Hakim Arhazzal <hakim.arhazzal@gmail.com>
ADD target/config-service-0.0.1-SNAPSHOT.jar config-service-0.0.1-SNAPSHOT.jar.jar
ENTRYPOINT ["java", "-jar", "/config-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 3333