FROM openjdk
MAINTAINER Hakim Arhazzal <hakim.arhazzal@gmail.com>
ADD target/DC_BACKEND-0.0.1-SNAPSHOT.jar DC_BACKEND-0.0.1-SNAPSHOT.jar.jar
ENTRYPOINT ["java", "-jar", "/DC_BackEnd-0.0.1-SNAPSHOT.jar"]
EXPOSE 2222