FROM openjdk
MAINTAINER Hakim Arhazzal <hakim.arhazzal@gmail.com>
ADD target/proxy-service-0.0.1-SNAPSHOT.jar proxy-service-0.0.1-SNAPSHOT.jar.jar
ENTRYPOINT ["java", "-jar", "/proxy-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 8761